name: Fix Upload Artifact

on:
  push:
    branches: [fix/github-actions]
  pull_request:
    branches: [main, develop]

jobs:
  test-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create test file
        run: echo "Test file content" > test.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-file
          path: test.txt
